name: Priority List
on:
  schedule: [{ cron: '0 2 * * 6' }]   # 02:00 (AM, UTC) Saturday
  workflow_dispatch:
jobs:
  priority-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.x' }
    - uses: iterative/priority-list@v1
      with:
        repos: >-
          echoix/grass
        github-token: ${{ secrets.GRASS_PRIORITY_PAT }} # must have read access to `repos`
        weight_activity: 14   # weight for number of comments
        weight_reactions: 7   # weight for reactions to original issue
        weight_staleness: 1   # weight for days of inactivity
        weight_age: 0.142857  # weight for days open
        multiplier_pr: 7      # weight multiplier for PRs (compared to issues)
        # weight multiplier for labels (negative to exclude)
        multiplier_labels: >-
          example:-1
          epic:0.142857
          blocked:0.142857
          invalid:0.142857
        p_label_graveyard: 4  # largest pN-label (lowest priority)
